version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ulisses
      POSTGRES_PASSWORD: 3532
      POSTGRES_DB: animedb
    ports:
      - "5433:5433"

